In [21]:
import numpy as np
import random 
import copy

In [2]:
def checkForOutOfBound(x,y,row,col):
    if x>=row or x<0 or y<0 or y>=col:
        return True
    return False
        

In [3]:
def matrixUpdate(grid,randRow,randCol,row,column):
    moves=np.array([[0,1],[1,0],[0,-1],[-1,0]])
    for move in moves:
        neighbourRow = randRow+move[0]
        neighbourCol = randCol+move[1]
        res = checkForOutOfBound(neighbourRow,neighbourCol,row,column)
        if res == False and not np.isnan(grid[neighbourRow,neighbourCol]) :
            grid[neighbourRow,neighbourCol] +=1 

In [5]:
row = 5
column = 5
grid = np.zeros([row,column], dtype = float)

In [6]:
grid

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
randRow = random.randint(1, row-2)
randCol = random.randint(1, column-2)
grid[randRow,randCol]=np.nan
matrixUpdate(grid,randRow,randCol,row,column)
grid

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 1., nan,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.]])

In [8]:
for i in range((row*column)//2):
    loop=0
    print(i)
    while loop<100:
        loop +=1
        randRow = random.randint(0, row-1)
        randCol = random.randint(0, column-1)
        print("printing random",randRow,randCol)
        if not np.isnan(grid[randRow,randCol]) and grid[randRow,randCol]==float(1):
            grid[randRow,randCol]=np.nan
            matrixUpdate(grid,randRow,randCol,row,column)  
            break
    
grid

0
printing random 0 2
printing random 2 0
printing random 0 4
printing random 2 3
printing random 4 2
printing random 0 0
printing random 3 1
printing random 4 3
printing random 4 1
1
printing random 3 3
printing random 1 2
printing random 1 4
printing random 3 1
printing random 1 2
printing random 2 3
printing random 1 3
printing random 4 0
2
printing random 3 3
printing random 4 1
printing random 4 2
3
printing random 2 0
printing random 0 0
printing random 1 1
printing random 3 1
printing random 3 4
printing random 2 0
printing random 0 0
printing random 0 4
printing random 2 0
printing random 2 0
printing random 0 3
printing random 1 3
printing random 2 3
printing random 2 0
printing random 4 2
printing random 1 4
printing random 3 0
printing random 2 3
printing random 3 4
printing random 4 4
printing random 2 2
printing random 0 2
printing random 1 4
printing random 3 1
printing random 1 3
printing random 1 3
printing random 4 1
printing random 2 0
printing random 2 2
printing ran

array([[ 0.,  1.,  1., nan,  1.],
       [ 2., nan,  3., nan,  2.],
       [nan, nan, nan, nan, nan],
       [ 3., nan,  3.,  2.,  1.],
       [nan, nan, nan, nan,  1.]])

In [9]:
intGrid = np.ones([row,column], dtype = int)
for r in range(row):
    for c in range(column):
        if np.isnan(grid[r,c]):
            intGrid[r,c]=0
intGrid    

array([[1, 1, 1, 0, 1],
       [1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1],
       [0, 0, 0, 0, 1]])

In [10]:
# openSpaces = np.empty(2,int)
# global openSpaces

# for r in range(row):
#     for c in range(column):
#         if intGrid[r,c] == 0:
#             ope=np.array([r,c])
#             openSpaces = np.vstack((openSpaces,ope))

# openSpaces = np.delete(openSpaces, 0, axis=0)
# openSpaces.shape
# openSpaces

In [11]:
# openSpaces.shape

In [12]:
# k=openSpaces.shape[0]
# k

In [13]:
openSpaces = []


for r in range(row):
    for c in range(column):
        if intGrid[r,c] == 0:
            
            openSpaces.append([r,c])
            
openSpaces

[[0, 3],
 [1, 1],
 [1, 3],
 [2, 0],
 [2, 1],
 [2, 2],
 [2, 3],
 [2, 4],
 [3, 1],
 [4, 0],
 [4, 1],
 [4, 2],
 [4, 3]]

In [22]:
def moveAlien(grid,openSpaces,aliens,row,column):
    moves=[[0,1],[1,0],[0,-1],[-1,0]]
    aliensCopy=copy.deepcopy(aliens)
    for alien in aliensCopy:
        print(alien)
        move=random.sample(moves,4)
        for move in moves:
            neighbourRow = alien[0]+move[0]
            neighbourCol = alien[1]+move[1]
            res = checkForOutOfBound(neighbourRow,neighbourCol,row,column)
            if [neighbourRow,neighbourCol] not in aliens and res == False and [neighbourRow,neighbourCol] in openSpaces:
                aliens.remove(alien)
                aliens.append([neighbourRow,neighbourCol])
                break
            
            

In [23]:
k=len(openSpaces)-2
while k>0:
    
    #aliens =np.random.choice(prog_langs, size=8)
#     print(np.random.choice(openSpaces, size=k))
    print(k)
    aliens=random.sample(openSpaces,k)
    
    print(aliens)
    print("gh")
    
    moveAlien(intGrid,openSpaces,aliens,row,column)
    
    
    k=k-1
#openSpaces

11
[[1, 3], [2, 2], [0, 3], [4, 2], [2, 1], [4, 0], [4, 3], [4, 1], [2, 4], [2, 3], [1, 1]]
gh
[1, 3]
[2, 2]
[0, 3]
[4, 2]
[2, 1]
[4, 0]
[4, 3]
[4, 1]
[2, 4]
[2, 3]
[1, 1]
10
[[4, 1], [1, 1], [1, 3], [3, 1], [4, 0], [2, 1], [0, 3], [2, 4], [2, 0], [4, 3]]
gh
[4, 1]
[1, 1]
[1, 3]
[3, 1]
[4, 0]
[2, 1]
[0, 3]
[2, 4]
[2, 0]
[4, 3]
9
[[4, 2], [2, 0], [1, 3], [4, 3], [3, 1], [2, 1], [4, 1], [0, 3], [2, 2]]
gh
[4, 2]
[2, 0]
[1, 3]
[4, 3]
[3, 1]
[2, 1]
[4, 1]
[0, 3]
[2, 2]
8
[[2, 3], [4, 2], [2, 1], [4, 1], [2, 2], [2, 0], [3, 1], [1, 3]]
gh
[2, 3]
[4, 2]
[2, 1]
[4, 1]
[2, 2]
[2, 0]
[3, 1]
[1, 3]
7
[[1, 3], [0, 3], [2, 3], [3, 1], [1, 1], [2, 2], [2, 4]]
gh
[1, 3]
[0, 3]
[2, 3]
[3, 1]
[1, 1]
[2, 2]
[2, 4]
6
[[2, 3], [1, 3], [0, 3], [4, 1], [3, 1], [1, 1]]
gh
[2, 3]
[1, 3]
[0, 3]
[4, 1]
[3, 1]
[1, 1]
5
[[2, 4], [0, 3], [1, 3], [3, 1], [2, 1]]
gh
[2, 4]
[0, 3]
[1, 3]
[3, 1]
[2, 1]
4
[[2, 0], [1, 3], [4, 1], [0, 3]]
gh
[2, 0]
[1, 3]
[4, 1]
[0, 3]
3
[[2, 0], [3, 1], [2, 4]]
gh
[2, 0]
[3, 1]
[2, 4]

In [ ]:
print(len(openSpaces))